# Generated by Django 4.1.4 on 2022-12-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='avatar',
            field=models.ImageField(upload_to='api/images/avatars'),
        ),
    ]
